[workspace]
members = [
	"fabricate", 
	"core"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Jaxson Pahukula <jaxpahu@gmail.com>"]
edition = "2021"
readme = "./README.md"
repository = "https://github.com/jaxsonp/FactoryScript"