[package]
name = "interpreter"
version.workspace = true
authors.workspace = true
edition.workspace = true
readme.workspace = true
default-run = "interpreter"

[dependencies]
fs-core = { path = "../fs-core" }
stdlib = { path = "../stdlib" }
clap = { version = "4.5.9", features = ["derive"] }
inline_colorization = "0.1.6"
regex = "1.10.5"
